### ISSUE TITLE
TensorFlow Requirement satisfied using TensorFlow GPU

### ISSUE THREAD

**Issue by sayandev** [appeler/ethnicolr#11]
I was trying to install ethnicolr-0.1.7 in a RHEL based GPU enable sever where tensorflow-gpu (1.2.1) is installed

$ pip list | grep "tensor"
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
tensorflow-gpu (1.2.1)
tensorflow-tensorboard (0.4.0)

Please let me know how can I override the tensorflow requirement with tensorflow-gpu

$ pip install -e ethnicolr-0.1.7
Obtaining file:///ssapfs/home/sayamait/python_packages/ethnicolr-0.1.7
Requirement already satisfied: pandas>=0.19.2 in /usr/lib64/python2.7/site-packa                                                                                                                                                             ges (from ethnicolr==0.1.7)
Requirement already satisfied: h5py>=2.7.0 in /ssapfs/home/sayamait/lib64/python                                                                                                                                                             2.7/site-packages (from ethnicolr==0.1.7)
Requirement already satisfied: Keras>=2.0.6 in /usr/lib64/python2.7/site-package                                                                                                                                                             s (from ethnicolr==0.1.7)
Requirement already satisfied: numpy>=1.12.1 in /usr/lib64/python2.7/site-packag                                                                                                                                                             es (from ethnicolr==0.1.7)
Collecting tensorflow>=1.1.0 (from ethnicolr==0.1.7)

**Comment by soodoku** [comment]
I think you are aware of this https://github.com/tensorflow/tensorflow/issues/7166

But @suriyan, any more concrete suggestions beyond that?

**Comment by sayandev** [comment]
Hi @soodoku ,
Thanks a lot for the pointer. It solved the problem.
I an closing the issue.
