### ISSUE TITLE
Tensorflow version 1.12.3

### ISSUE THREAD

**Issue by zhangchi1** [appeler/ethnicolr#16]
Hello, I think I still got the error message "ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.3 (from ethnicolr) " when I try to pip install ethnicolr. Anything I can do to fix this issue? Thanks

**Comment by suriyan** [comment]
Hello, What is the platform (Python and OS version) that you're trying to install?

**Comment by zhangchi1** [comment]
Hello, I am using Mac Mojave 10.14.4, with Python 3.7.3, Tensorflow 1.13.1. Thanks for the help.

**Comment by suriyan** [comment]
Actually, can you try force update the TensorFlow to version 1.12.3 or below by the following command?
`pip install -U "tensorflow<=1.12.3"`

Thanks.

**Comment by zhangchi1** [comment]
Hi, I think I tried that pip command before and i got this message 
```
ERROR: Could not find a version that satisfies the requirement tensorflow<=1.12.3 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
ERROR: No matching distribution found for tensorflow<=1.12.3
```
I think TensorFlow doesn't allow us to downgrade the TensorFlow version to 1.12?

**Comment by suriyan** [comment]
Ok, so I think you can force downgrade with `-U` option.

**Comment by zhangchi1** [comment]
okay, thanks.

**Comment by eyvindwa** [comment]
Hi,

I have the same issue. I try using the -U option to force a specific version, but it seems this is no longer available. Here is my command line, and the response:

`>py -m pip install -U "tensorflow<=1.12.3"
Collecting tensorflow<=1.12.3
  ERROR: Could not find a version that satisfies the requirement tensorflow<=1.12.3 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
ERROR: No matching distribution found for tensorflow<=1.12.3`

**Comment by eyvindwa** [comment]
For anyone else coming across this, the only solution I could find was to install a version of ethnicolr that did not have an explicit requirement on the tensorflow version:

`>py -m pip install ethnicolr==0.2.0`

**Comment by dhimmel** [comment]
When installing ethnicolr==0.2.4 from PyPI, I got this error:

```
  ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.3 (from ethnicolr) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0)
ERROR: No matching distribution found for tensorflow==1.12.3 (from ethnicolr)
```

But I see a recently merged PR https://github.com/appeler/ethnicolr/pull/17 updates the tenserflow version, so I will switch to installing from GitHub.

It's a problem IMO for this package to specify exact version dependencies rather than testing against the latest. This makes it difficult to install this package in an environment is meant to do other things (lest my pandas version get downgraded to 0.19.2).
