### ISSUE TITLE
Got the following error when executing a dataframe. Latest keras installed.

### ISSUE THREAD

**Issue by Dragut** [appeler/ethnicolr#18]
TypeError                                 Traceback (most recent call last)
<ipython-input-282-99fc2aaef271> in <module>
      3 dataset = pd.DataFrame({'lastname': df[:]}) # from list to dataframe
      4 #dataset.drop(['_last_name'], axis=1,inplace=True)
----> 5 pred_census_ln(dataset, 'lastname')
      6 # ClaimPerson1=pd.merge(ClaimPerson1,dataset,left_on='lastname',right_on='lastname',how='left')
      7 # ClaimPerson1[ClaimPerson1.race.isnull()]

~/anaconda3/lib/python3.6/site-packages/ethnicolr/pred_census_ln.py in pred_census_ln(cls, df, namecol, year)
     73             cls.race = rdf.race.tolist()
     74 
---> 75             cls.model = load_model(MODEL.format(year))
     76 
     77         # build X from index of n-gram sequence

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in load_model(filepath, custom_objects, compile)
    417     # Arguments
    418         filepath: The location to check.
--> 419     """
    420     return isinstance(filepath, string_types) and filepath.startswith('gs://')
    421 

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in _deserialize_model(f, custom_objects, compile)
    223 def _deserialize_model(h5dict, custom_objects=None, compile=True):
    224     """De-serializes a model serialized via _serialize_model
--> 225 
    226     # Arguments
    227         h5dict: `keras.utils.hdf5_utils.HFDict` instance.

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in model_from_config(config, custom_objects)
    456 
    457     This decorator parses the `filepath` argument of the `load_function` and
--> 458     fetches the required object from GCS if `filepath` starts with "gs://".
    459 
    460     Note: the file is temporarily copied to local filesystem from GCS before loaded.

~/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53 from .convolutional import UpSampling3D
     54 from .convolutional import ZeroPadding1D
---> 55 from .convolutional import ZeroPadding2D
     56 from .convolutional import ZeroPadding3D
     57 

~/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    143             if has_arg(cls.from_config, 'custom_objects'):
    144                 return cls.from_config(
--> 145                     config['config'],
    146                     custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
    147                                         list(custom_objects.items())))

~/anaconda3/lib/python3.6/site-packages/keras/engine/sequential.py in from_config(cls, config, custom_objects)
    299         for conf in layer_configs:
    300             layer = layer_module.deserialize(conf,
--> 301                                              custom_objects=custom_objects)
    302             model.add(layer)
    303         if not model.inputs and build_input_shape:

~/anaconda3/lib/python3.6/site-packages/keras/engine/sequential.py in add(self, layer)
    179                 self.outputs = [layer._inbound_nodes[-1].output_tensors[0]]
    180                 self.inputs = network.get_source_inputs(self.outputs[0])
--> 181         elif self.outputs:
    182             output_tensor = layer(self.outputs[0])
    183             if isinstance(output_tensor, list):

~/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py in __call__(self, inputs, initial_state, constants, **kwargs)
    530         if hasattr(self.cell.state_size, '__len__'):
    531             return [K.tile(initial_state, [1, dim])
--> 532                     for dim in self.cell.state_size]
    533         else:
    534             return [K.tile(initial_state, [1, self.cell.state_size])]

~/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    455                     else:
    456                         raise ValueError('You tried to call layer "' +
--> 457                                          self.name +
    458                                          '". This layer has no information'
    459                                          ' about its expected input shape, '

~/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py in call(self, inputs, mask, training, initial_state)
   2192                  bias_constraint=None,
   2193                  dropout=0.,
-> 2194                  recurrent_dropout=0.,
   2195                  implementation=2,
   2196                  return_sequences=False,

~/anaconda3/lib/python3.6/site-packages/keras/layers/recurrent.py in call(self, inputs, mask, training, initial_state, constants)
    647                              'time dimension is undefined. \n'
    648                              '- If using a Sequential model, '
--> 649                              'specify the time dimension by passing '
    650                              'an `input_shape` or `batch_input_shape` '
    651                              'argument to your first layer. If your '

~/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in rnn(step_function, inputs, initial_states, go_backwards, mask, constants, unroll, input_length)
   3009                                      **kwargs)
   3010 
-> 3011 
   3012 @symbolic
   3013 def gradients(loss, variables):

TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

**Comment by suriyan** [comment]
Please try the latest version `pip install -U ethnicolr==0.3.0` We strongly recommend installing inside the Python virtualenv and/or make sure all dependencies version are met the [requirements.txt](https://github.com/appeler/ethnicolr/blob/master/requirements.txt)
