### ISSUE TITLE
Unable to install on Ubuntu

### ISSUE THREAD

**Issue by AdityaAnand1** [appeler/ethnicolr#30]
![image](https://user-images.githubusercontent.com/13274079/86603404-92c1f700-bfc1-11ea-9b19-f63c93f00a65.png)

Any fixes? This is just a plain `pip install ethnicolr`

**Comment by andret6** [comment]
Heya, what version of python are you using? I had this issue before on windows and was able to resolve by downgrading to 3.7 and installing the requisite versions of tensorflow and keras
