### ISSUE TITLE
strange characters in wiki_data

### ISSUE THREAD

**Issue by MaryFllh** [appeler/ethnicolr#33]
Looking at wiki_name_race.csv which is produced by wikilabels-name-race.py it appears that the encoding if utf-8 but I'm having trouble understanding weird characters in the names such as `mojÅ¾Ã­Å¡` and `pÃ¶pperle`, `bodnä\x83raå\x9f`, these to seem to appear in the same fashion in the zipped raw dataset. I've tried other encodings but none seem to work. Is there a better way to present these strings?
Thanks

**Comment by suriyan** [comment]
Sorry, I just realize that. These weird characters are Non-English characters in the names. You're right, it's same fashion in the original dataset, I also have no idea to dealing with this issue.
