### ISSUE TITLE
what do pctapi, pctaian, pct2prace stand for?

### ISSUE THREAD

**Issue by nabsabraham** [appeler/ethnicolr#34]
thanks for your contribution! 
I flipped through the docs and I see `pctapi` is defined as "percentage chance asian" but then what is `pctaian`? and I couldn't figure out what `pct2prace` stands for. Could you please let me know?

**Comment by soodoku** [comment]
https://github.com/appeler/ethnicolr/blob/master/ethnicolr/data/census/census_2000.pdf

**Comment by joowonpark** [comment]
It is in page 17: pctaian is for American Indian and Alaskan Native, and pct2prace is for two or more races.
