### ISSUE TITLE
Dont use race prediction

### ISSUE THREAD

**Issue by jeremyholtzman** [appeler/ethnicolr#35]
I just qa-ed the wikipedia and census results on race using a north carolina file with known races. The wikipedia and census predictions were correct 72% of the time, which wasn't bad, except they predicted almost no black people. Almost all of the errors came from incorrectly assuming black people were white

I just checked the Florida Voters as well, and it does a better job (78% accurate), but still only gets black people correct 30% of the time.

**Comment by soodoku** [comment]
Thank you for doing this @jeremyholtzman! Long been on my radar to see how the success translates across states. @suriyan --- probably a good time to do this also along w/ our new function. 

Questions for you = 

1. we have two census functions. one is a pred_ and another is simply census_ln. which one did you use?  
2. did you are use probability estimates or just .5 as cutoff or most probable. (its ok to do any of it but my bet would be on prob. to do the best.)

My email is easily findable --- http://gsood.com/research/papers/pwned.pdf, for instance --- and it would be great to see the ipynb. We can add a separate repo. in the org. to which you can post some of the results and we can build from there.

**Comment by jeremyholtzman** [comment]
Hey @soodoku 

For the wikipeida test, I used `pred_wiki_name`. For Census, I used `pred_census_ln` with a 2010 flag. For FL reg, I used `pred_fl_reg_name`. 

I did just use the api's resulting best guess at race for comparison instead of each of the individual probability. I do worry though about the classification imbalance due to the overwhelming number of white people in some of these underlying datasets, which is why I'm trying to now just use these APIs as inputs for my own model instead of trusting the results on their own.

**Comment by soodoku** [comment]
Thx!

Re. imbalance, one issue is calibration. The predictions are calibrated.

**Comment by soodoku** [comment]
all right. Eval. on NC + models based on NC here: https://github.com/appeler/nc_race_ethnicity

**Comment by marcmaxson** [comment]
Because the surnames of former slaves and former enslavers are often the same, this model will never be that good at separating the two. But there exists 19th-century insurance registries with all the names of former slaves/enslavers that I was going to use to exclude those names from the set (as inherently ambiguous) -- could you update your code to do this too? I could point you to the resources.

**Comment by marcmaxson** [comment]
I'm happy to collaborate on this project. While the model is considered too sensitive and not accurate enough for my work, I think this improvement will limit others making erroneous assumptions with the model. 

For names of former slaves/enslavers, I suggest a kwarg option for categorizing these as "undetermined."

We can get a master list of all former slave surnames and former slaveowners from historical insurance company registries 
- [New York Life](https://www.nypl.org/locations/schomburg/jbh-research-and-reference-division) 
- [California](https://www.insurance.ca.gov/01-consumers/150-other-prog/10-seir/)
- [slave names - CA](https://www.insurance.ca.gov/01-consumers/150-other-prog/10-seir/upload/Slave-Names-Registry.pdf), 
- [slaveholder names - CA](https://www.insurance.ca.gov/01-consumers/150-other-prog/10-seir/upload/Registry-of-Slaveholder-Names.pdf)
- [illinois](https://idoi.illinois.gov/content/dam/soi/en/web/insurance/sites/insurance/reports/reports/slavepoliciesreports.pdf),
- [20 other states](https://genealogytrails.com/main/slaveinsurance2.html#nc)
- [1700 congressmen](https://github.com/washingtonpost/data-congress-slaveowners/)

The main task is to collate these into one long list of names, then probably use the frequency of each surname to assign a probability that the name is "undetermined." This also only applies to data from US populations.
