### ISSUE TITLE
Arguments for pred_wiki_name

### ISSUE THREAD

**Issue by HanyinWang** [appeler/ethnicolr#38]
Thanks for sharing the excellent repository.

I'm wondering what are the argument names for the middle name and suffix in `pred_wiki_name`?

Thanks

**Comment by soodoku** [comment]
-f first_name -l last_name

where first_name and last_name can be name or index location of column containing the info.

```
 parser.add_argument('-f', '--first', required=True,
                        help='Name or index location of column contains '
                             'the first name')
    parser.add_argument('-l', '--last', required=True,
                        help='Name or index location of column contains '
                             'the last name')
```

**Comment by HanyinWang** [comment]
I know the arguments for first name and last name, I wanted to ask the argument names for **middle name** and **suffix**. According to the description: "name or location of the column containing the first name, last name, middle name, and suffix, if there.", but there's nowhere to claim the columns for middle name and suffix. Thanks.

**Comment by soodoku** [comment]
They are not used

**Comment by m7mdshalfa** [comment]
I am trying to run this to predict race for couple names

testframe={'Lastname':['Shyr','Fierros'],
          'Fname':['Shyr','Fierros']}

pdf=pd.DataFrame(testframe,columns=['Lastname','Fname'])

ethnicolr.pred_wiki_ln(pdf,'Lastname')


I got an error

TypeError: Expected int32, got -0.05 of type 'float' instead.

in tensor_util.py, line 371, in _AsserCompatible

dtype.name, repr(mismatch), type(mismatch).__name__))

Same error occurred when calling pred_census_ln, but census_ln worked fine

Any idea what is wrong?
