### ISSUE TITLE
Report errors when use keras version >= 2.0.6

### ISSUE THREAD

**Issue by Simon-KALIDO** [appeler/ethnicolr#5]
The following error is reported when keras 2.0.6 or keras 2.0.8 is used.

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("embedding_1/random_uniform:0", shape=(2260, 32), dtype=float32)'

This error sourced back to line "model = load_model(MODEL)" in function "pred_wiki_name".

By switching to keras 2.0.5, it is then working. However, it would be better if this library can be updated along with keras. I reckon the solution is easy and you might just need to update your keras, retrain the model and redeploy it. Please let me know if I am wrong. 

Thank you!

**Comment by suriyan** [comment]
fixed in #9
