### ISSUE TITLE
What is `(S)` in the output probability?

### ISSUE THREAD

**Issue by zhiyzuo** [appeler/ethnicolr#6]
Thank you for providing this package! 

I was playing with it and found a confusing output as shown below:
![image](https://user-images.githubusercontent.com/7501149/36357945-75a043d2-14cb-11e8-978d-5714f21b3155.png)

I did not see any explanations on it in the documentation though.

**Comment by suriyan** [comment]
Welcome and thank you for your question. `(S)` means  `Some Other Race` Please look at the [readme.md].(https://github.com/appeler/ethnicolr/blob/master/ethnicolr/data/census/readme.md#census-last-name-data)

**Comment by zhiyzuo** [comment]
I see. Thank you!
