### ISSUE TITLE
Why out-of-vocabulary patterns are set index=0

### ISSUE THREAD

**Issue by mocherson** [appeler/ethnicolr#60]
https://github.com/appeler/ethnicolr/blob/f41f9a22a67f9bd6327a24374f445470ef30c417/ethnicolr/utils.py#L85

As vocab[0] is the most frequent pattern, here setting an out-of-vocabulary pattern index 0 seems not to make sense.

**Comment by soodoku** [comment]
good pt.! thank you! will fix.

**Comment by suriyan** [comment]
Thanks for pointing that out. I just added a special token UNK for out-of-vocabulary at index 0 to make better sense.
