### ISSUE TITLE
many Null values

### ISSUE THREAD

**Issue by barslan16** [appeler/ethnicolr#64]
I used 
`odf = pred_wiki_name(df, 'lastname' , 'firstname')`

It gives NaN values for 6500 rows out of a dataset of approximately 10000 rows.
<img width="902" alt="Screen Shot 2022-05-09 at 01 36 17" src="https://user-images.githubusercontent.com/55951610/167318595-07fb732f-cc56-4fb9-9b0f-27193208bf80.png">

**Comment by soodoku** [comment]
will need more data. for instance, a sample of the entries.

**Comment by barslan16** [comment]
> will need more data. for instance, a sample of the entries.

I just realized that the problem is caused by the indexes of my dataframe. Thanks for your quick reply!
