### ISSUE TITLE
Failed docker build due to tensorflow=2.5.0 dependency

### ISSUE THREAD

**Issue by Erin-Boehmer** [appeler/ethnicolr#70]
My docker build is failing because ethnicolor (using 0.7.0) depends on tensorflow==2.5.0. Building on top of `python:3.8-slim-buster` Docker image.

I see on pip the ethnicolor build is failing for the same issue https://pypi.org/project/ethnicolr/ ([failed tests](https://github.com/appeler/ethnicolr/actions/runs/2427262219))

Errors in the docker build output:
```
ERROR [4/5] RUN pip3 install -r /usr/local/release.txt  
------
 > [4/5] RUN pip3 install -r /usr/local/release.txt:
#8 1.083 Collecting ethnicolr==0.7.0
#8 1.190   Downloading ethnicolr-0.7.0-py2.py3-none-any.whl (36.8 MB)
#8 1.929      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.8/36.8 MB 43.8 MB/s eta 0:00:00
#8 2.602 Collecting pandas>=1.1.5
#8 2.632   Downloading pandas-1.4.2-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (11.0 MB)
#8 2.876      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 45.6 MB/s eta 0:00:00
#8 3.398 ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.0 (from ethnicolr) (from versions: none)
#8 3.398 ERROR: No matching distribution found for tensorflow==2.5.0
```

**Comment by suriyan** [comment]
Please try the latest version `ethnicolr==0.9.0`

**Comment by Erin-Boehmer** [comment]
Unfortunately the 0.9.0 still errors on dependencies for the M1. Looking at the workaround now.

```
 > [4/5] RUN pip3 install -r /usr/local/release.txt:
#8 0.939 Collecting ethnicolr==0.9.0
#8 7.292   Downloading ethnicolr-0.9.0-py2.py3-none-any.whl (36.8 MB)
#8 12.64      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.8/36.8 MB 10.2 MB/s eta 0:00:00
#8 13.19 ERROR: Could not find a version that satisfies the requirement tensorflow<3,>=2.7.2 (from ethnicolr) (from versions: none)
#8 13.19 ERROR: No matching distribution found for tensorflow<3,>=2.7.2
```

**Comment by suriyan** [comment]
Please try to install AArch64 version of tensorflow by the following Docker command:-

`RUN pip3 install "tensorflow-aarch64<3,>=2.7.2"`

Please also make sure you put it before:-

`RUN pip3 install -r /usr/local/release.txt`

**Comment by suriyan** [comment]
Please ignore above and try the latest version `ethnicolr==0.9.1`. I just added the platform specific dependencies for `tensorflow` package.

**Comment by suriyan** [comment]
@Erin-Boehmer, let me close this issue. Please feel free to open it again if you still can't install the latest version (0.9.1) on your machine. Thank you.
