### ISSUE TITLE
update conda package?

### ISSUE THREAD

**Issue by jwlockhart** [appeler/ethnicolr#73]
It looks like [this package](https://anaconda.org/soodoku/ethnicolr) has not been updated in the anacoda channels since `v0.1.5`, and is only marked for windows. Will the devs please consider updating it in conda and adding noarch or linux versions?

**Comment by suriyan** [comment]
We are no longer plan to release the package on anaconda channel.

Actually, we can install `ethnicolr` package from PyPI under conda environment.
