### ISSUE TITLE
How to cite you in an academic paper?

### ISSUE THREAD

**Issue by Michael-E-Rose** [appeler/ethnicolr#92]
We use ethnicolr in a scientific study and want to cite you. How would you like us to cite you? Is there a paper or anything?

**Comment by soodoku** [comment]
Hey, thank you so much for using our software! 

On GitHub, you will see a 'cite this repo.' on the right-hand side. But here's the file it generates (you can use chatgpt to get the bibtex version.) 

Laohaprapanon, S., Sood, G., & Naji, B. (2022). ethnicolr: Predict Race and Ethnicity From Name (Version 0.9.1) [Computer software]. https://github.com/appeler/ethnicolr

We do have a paper. The v1 of the paper maps to this repo. 

https://arxiv.org/abs/1805.02109

@article{sood2018predicting,
  title={Predicting race and ethnicity from the sequence of characters in a name},
  author={Sood, Gaurav and Laohaprapanon, Suriyan},
  journal={arXiv preprint arXiv:1805.02109},
  year={2018}
}

The v2 is technically associated with ethnicolr2: https://github.com/appeler/ethnicolr2/
